import type { FortyTwoApi } from "@/lib/forty-two/api";
import { cachedOnce } from "@/lib/memory-cache";
import { POOL_CURSUS_ID } from "@/lib/forty-two/live-campus";

/**
 * How often a student's own corrections end in a pass.
 *
 * Checked against the cron that used to fill this column, which is still on
 * disk as refresh-42/src/correction.js. That matters, because the definition
 * is not obvious and two reasonable readings disagree by nine points: hbelle
 * is 84% by the old rule and 75% by a plain "mark of 50 or more". This
 * follows the old rule, so the number means what it has always meant here.
 *
 * The rule, from that file:
 *
 *   - piscine evaluations do not count at all, either way
 *   - a pass is a positive flag AND a final mark of 80 or more
 *   - everything else that counts is a fail
 *
 * One addition: the evaluations that belong to a work experience -- the peer
 * video of an internship, an apprenticeship's company reviews -- are left out
 * too. They are presentations, not corrections of code, and they are nearly
 * always passed: kiroussa's nine of them alone moved the figure from 58% to
 * 60%.
 *
 * The flag is the part a mark alone misses. "Crash", "Cheat", "Leaks",
 * "Norme", "Forbidden Function", "Empty work" are all verdicts, and a mark on
 * its own does not say which of them happened.
 *
 * One departure: an evaluation with no mark is booked, not judged, and the
 * cron counted it as a fail. It is left out here.
 *
 * The cost is why this is possible at all. scale_teams cannot be filtered by
 * corrector, so working the column out campus-wide meant reading all 108813 of
 * Nice's evaluations, 1089 pages. /v2/users/:id/scale_teams/as_corrector
 * answers for one person, and a student has a median of 49 corrections -- one
 * page. A campus of 739 is 739 requests rather than 1089 pages.
 */

/** The old cron's threshold, kept so the figure stays comparable. */
const PASS_MARK = 80;

/** Piscine projects change; the list of them should not be written down. */
const PISCINE_PROJECTS_TTL = 7 * 24 * 60 * 60;

/** A ratio moves one evaluation at a time. */
const CACHE_TTL = 6 * 60 * 60;

/** A student with more corrections than this is having them counted anyway. */
const MAX_PAGES = 8;

export interface CorrectionRatio {
  positive: number;
  negative: number;
  percentage: number;
}

/**
 * The projects that do not count, worked out rather than listed.
 *
 * The cron read these from a cursus9_projects_output.json generated by hand.
 * It held 31 ids; the cursus holds 34 today, the three new ones being the
 * exam checkpoints added since. Asking is one request a week and cannot go
 * stale the way the file did.
 */
const piscineProjectIds = async (api: FortyTwoApi): Promise<Set<number>> =>
  cachedOnce("piscine-projects", PISCINE_PROJECTS_TTL, async () => {
    const rows = await api.fetchAllPages(`/cursus/${POOL_CURSUS_ID}/projects`, {
      maxPages: 3,
    });

    return new Set<number>(
      rows
        .map((row) => row?.id)
        .filter((id): id is number => typeof id === "number"),
    );
  });

/**
 * The work experiences, as the parents of the evaluations they carry.
 *
 * Their sub-projects are not in the cursus listing this site ships, so they
 * are asked for -- one request, since filter[id] takes the lot, and the answer
 * changes about as often as the piscine's.
 */
const EXPERIENCE_PROJECT_IDS = [1638, 1644, 1662, 1873, 1857, 1865];

const experienceProjectIds = async (api: FortyTwoApi): Promise<Set<number>> =>
  cachedOnce("experience-projects", PISCINE_PROJECTS_TTL, async () => {
    const response = await api.fetch(
      `/projects?filter[id]=${EXPERIENCE_PROJECT_IDS.join(",")}&page[size]=100`,
    );
    const rows = response.ok ? await response.json() : [];

    const ids = new Set<number>(EXPERIENCE_PROJECT_IDS);
    for (const row of Array.isArray(rows) ? rows : []) {
      for (const child of row?.children ?? []) {
        if (typeof child?.id === "number") ids.add(child.id);
      }
    }

    return ids;
  });

export const getCorrectionRatio = async (
  userId: number,
  api: FortyTwoApi,
): Promise<CorrectionRatio> =>
  cachedOnce(`correction-ratio:v3:${userId}`, CACHE_TTL, async () => {
    const [piscine, experience, rows] = await Promise.all([
      piscineProjectIds(api),
      experienceProjectIds(api),
      api.fetchAllPages(`/users/${userId}/scale_teams/as_corrector`, {
        maxPages: MAX_PAGES,
      }),
    ]);

    const excluded = new Set<number>([...piscine, ...experience]);

    let positive = 0;
    let negative = 0;

    for (const row of rows) {
      const projectId = row?.team?.project_id;
      if (typeof projectId !== "number" || excluded.has(projectId)) continue;

      // Booked, not judged.
      if (row.final_mark === null || row.final_mark === undefined) continue;

      if (row.flag?.positive === true && row.final_mark >= PASS_MARK) positive++;
      else negative++;
    }

    const total = positive + negative;

    return {
      positive,
      negative,
      percentage: total ? Math.round((positive / total) * 100) : 0,
    };
  });
