import type { FortyTwoProject, FortyTwoTitle, FortyTwoCursus } from "@/types/forty-two"

export const mockProjects: Record<number, FortyTwoProject> = {
  1: {
    id: 1,
    name: "Libft",
    experience: 462,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  2: {
    id: 2,
    name: "ft_printf",
    experience: 882,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  3: {
    id: 3,
    name: "get_next_line",
    experience: 882,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  4: {
    id: 4,
    name: "Born2beroot",
    experience: 577,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  5: {
    id: 5,
    name: "so_long",
    experience: 1050,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  6: {
    id: 6,
    name: "push_swap",
    experience: 1575,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  7: {
    id: 7,
    name: "minishell",
    experience: 2520,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  8: {
    id: 8,
    name: "Philosophers",
    experience: 1575,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  9: {
    id: 9,
    name: "NetPractice",
    experience: 1050,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  10: {
    id: 10,
    name: "cub3d",
    experience: 2520,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  11: {
    id: 11,
    name: "CPP Module 00",
    experience: 462,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  12: {
    id: 12,
    name: "CPP Module 01",
    experience: 462,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  13: {
    id: 13,
    name: "CPP Module 02",
    experience: 462,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  14: {
    id: 14,
    name: "CPP Module 03",
    experience: 462,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  15: {
    id: 15,
    name: "CPP Module 04",
    experience: 462,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  16: {
    id: 16,
    name: "Inception",
    experience: 2310,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  17: {
    id: 17,
    name: "webserv",
    experience: 2520,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
  18: {
    id: 18,
    name: "ft_transcendence",
    experience: 5775,
    is_validated: false,
    status: "not_started",
    mark: 0,
    children: [],
  },
}

export const mockTitles: FortyTwoTitle[] = [
  {
    title: "Expert en architecture informatique",
    type: "rncp-7",
    level: 21,
    numberOfEvents: 14,
    numberOfExperiences: 4,
    numberOfSuite: 3,
    experience: {
      1: true,
      2: true,
      3: true,
      4: true,
    },
    options: [
      {
        title: "Option 1",
        experience: 15000,
        numberOfProjects: 5,
        projects: {
          5: mockProjects[5],
          6: mockProjects[6],
          7: mockProjects[7],
          8: mockProjects[8],
          9: mockProjects[9],
        },
      },
      {
        title: "Option 2",
        experience: 15000,
        numberOfProjects: 5,
        projects: {
          10: mockProjects[10],
          11: mockProjects[11],
          12: mockProjects[12],
          13: mockProjects[13],
          14: mockProjects[14],
        },
      },
    ],
    suite: {
      15: mockProjects[15],
      16: mockProjects[16],
      17: mockProjects[17],
      18: mockProjects[18],
    },
  },
  {
    title: "Développeur logiciel",
    type: "rncp-6",
    level: 18,
    numberOfEvents: 10,
    numberOfExperiences: 3,
    numberOfSuite: 2,
    experience: {
      1: true,
      2: true,
      3: true,
    },
    options: [
      {
        title: "Option 1",
        experience: 10000,
        numberOfProjects: 4,
        projects: {
          5: mockProjects[5],
          6: mockProjects[6],
          7: mockProjects[7],
          8: mockProjects[8],
        },
      },
      {
        title: "Option 2",
        experience: 10000,
        numberOfProjects: 4,
        projects: {
          9: mockProjects[9],
          10: mockProjects[10],
          11: mockProjects[11],
          12: mockProjects[12],
        },
      },
    ],
    suite: {
      16: mockProjects[16],
      17: mockProjects[17],
    },
  },
]

export const mockCursus: FortyTwoCursus = {
  level: 15.5,
  events: 8,
  projects: mockProjects,
}
