name: Auto Commit every 30 minutes

on:
  schedule:
    - cron: '*/30 * * * *'
    
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AUTO_COMMIT }}

      - name: Modify a file to trigger a commit
        run: |
          echo " " >> ./tmp.txt

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto commit to trigger Vercel rebuild"
          git push https://x-access-token:${{ secrets.AUTO_COMMIT }}@github.com/fZpHr/42insight.git HEAD:main --force
